# Generated by Django 6.0 on 2025-12-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
