# Generated by Django 6.0 on 2025-12-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_app_description_az_app_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='apk_filename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='app',
            name='apk_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
