# Generated by Django 6.0 on 2026-01-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_app_created_at_app_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
