# Generated by Django 6.0 on 2026-01-05 18:59

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_app_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='apps.app')),
            ],
        ),
    ]
