# Generated by Django 6.0 on 2025-12-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_category_service_is_active_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_ru',
        ),
    ]
