# Generated by Django 6.0 on 2025-12-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_category_name_az_remove_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
