# Generated by Django 6.0 on 2025-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_subcategory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
